---
# tasks file for Deploy_Go
- hosts: GoApp
  become: true

  vars:
    go_apps_location: /usr/local/go
    golang_package: go1.17.7.linux-amd64.tar.gz
  tasks:
    - name: Download Golang
      get_url:
        url: https://dl.google.com/go/{{ golang_package }}
        dest: /tmp/{{ golang_package }}
    - name: Unarchive {{ golang_package }}
      unarchive:
        remote_src: yes
        src: /tmp/{{ golang_package}}
        dest: /tmp
    - name: Copy go folder to server.
      copy: "remote_src=yes src=/tmp/go dest=/usr/local"

    - name: modify .bashrc
      become_user: user
      blockinfile:
        dest: ~/.bashrc
        block: |
          export GOPATH={{ go_apps_location }}
          export GOROOT={{ go_apps_location }}
          export GOBIN=/usr/bin
          export PATH=$GOBIN:$PATH:/usr/local/go/bin
        insertafter: EOF
        create: yes
 #   - name: Source the ~/.bashrc file
  #    become_user: user
   #   shell: source ~/.bashrc

    - name: Ensure Go app folder exists.
      file: "path={{ go_apps_location }} state=directory mode=0777"

    - name: Copy go app to server.
      copy: "src=../../example-go-api dest={{ go_apps_location }}/src"

    - name: Download Dependencies
      command: go get {{ go_apps_location }}/src/example-go-api
    - name: Run the go app
      command: go run {{ go_apps_location }}/src/example-go-api/main.go
